name: CreativeChessAI CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint Python Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install pylint
      - name: Run Pylint
        run: |
          pylint main.py db_config.py || true  # tolère des warnings

  test:
    name: Test App Logic
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: creativechessai
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Wait for MySQL to be ready
        run: sleep 20

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Create DB structure
        run: |
          mysql -h 127.0.0.1 -uroot -proot creativechessai < schema.sql

      - name: Run the script
        env:
          DB_HOST: 127.0.0.1
          DB_USER: root
          DB_PASSWORD: root
          DB_NAME: creativechessai
        run: |
          python data_neural_training.py

  notify:
    name: Notify success
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Send notification (placeholder)
        run: echo " CreativeChessAI pipeline succeeded!"
